### ISSUE TITLE
Add option to allow reusing of numbers

### ISSUE THREAD

**Issue by thewilli** [rosmo/terraform-provider-persistent#50]
I want to use this resource to provide fixed network assignments for resources. All resources should always get the same network assigned, but if a resource was decommissioned, I'd like that particular number to be reassigned.

Please consider an optional `reuse` parameter defaulting to false (current behaviour). If enabled, unassigned numeric values would be assigned to new keys.

Would you consider implementing this or accept a PR?

Thanks

**Comment by rosmo** [comment]
I'd be very happy to take a PR. I might be able to look at it too at some point if you are too busy.

**Comment by rosmo** [comment]
Thank you, just pushed out a new release (0.2.0)!
